export const consts = {
  GET_COUNTRIES: 'GET_COUNTRIES',
  GET_INPUT: 'GET_INPUT',
  GET_GLOBAL_DATA: 'GET_GLOBAL_DATA',
  GET_SUMMARY_COUNTRIES: 'GET_SUMMARY_COUNTRIES',
  GET_CURRENT_COUNTRIE: 'GET_CURRENT_COUNTRIE',
  GET_ACTION_CURRENT: 'GET_ACTION_CURRENT',
  GET_SEARCH_COUNTRIE: 'GET_SEARCH_COUNTRIE',
  GET_CURRENT_GISTORY: 'GET_CURRENT_GISTORY',
  GET_FILTER: 'GET_FILTER',
  INPUT_SELECT_DATA: 'INPUT_SELECT_DATA',
  SHOW_MENU_MOVIL: 'SHOW_MENU_MOVIL'
}
